# Конфигурация API ключей для Ephemeris Decoder
# ВНИМАНИЕ: Этот файл содержит хеши API ключей для безопасного хранения
# Никогда не коммитьте реальные API ключи в репозиторий!

# Демо-конфигурация для тестирования
# Для продакшена замените демо-ключ на реальные ключи

api_keys:
  - key_id: "demo_key_001"
    name: "Demo Key for Testing"
    key_hash: "c3499c2729730a7f807efb8676a92dcb6f8a3f8f0675b48a019df2f4209e23"  # Хеш демо-ключа
    permissions:
      - "read"
    created_at: "2024-01-15T12:00:00"
    expires_at: null  # Бессрочный для демо
    is_active: true
    rate_limit: 1000
    usage_count: 0

# Информация о безопасности
notes:
  - "Это демо-конфигурация. Замените на реальные ключи для продакшена"
  - "Демо-ключ: замените_этот_ключ_на_реальный_64_символьный_hex_ключ"
  - "Используйте utils/auth.py для генерации новых ключей"
  - "Храните API ключи в секрете!"
  - "Регулярно меняйте ключи для безопасности"

# Настройки безопасности
security:
  enable_rate_limiting: true
  max_requests_per_minute: 100
  enable_ip_filtering: false
  allowed_ips: []

# Инструкции по использованию
usage:
  - "Для генерации нового ключа запустите: python utils/auth.py"
  - "Для тестирования используйте демо-ключ из вывода программы"
  - "В продакшене отключите демо-ключи"
  - "Мониторьте использование ключей через /admin/keys эндпоинт"
